---
- name: Get the node's details
  command: >-
    {{ bin_dir }}/kubectl get node
    {{ kube_override_hostname|default(inventory_hostname) }}
    -o json
  register: kubectl_get_node
  delegate_to: "{{ groups['kube-master'][0] }}"
  failed_when: false
  changed_when: false

- name: Update Node
  block:
    - name: Cordon & drain node
      include_tasks: drain.yml

    - name: Upgrade the Operating System
      include_tasks: ubuntu.yml

    - name: Uncordon node
      include_tasks: uncordon.yml
